name: CI/CD Pipeline - Discount Calculation

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name:  Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-restore --logger trx --results-directory TestResults

      - name: Upload Test Results (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults

 
